A01V3      20Meet Entries                  Hy-Tek, Ltd               8.0FHy-Tek, Ltd         252-633-517712272021                                    TM41    N21
B11        Christmas Time Trial                                                      Aura Dundalk                        1228202112302021            S       N10
C11          ADSCAura Dundalk Swimming Club    ADSC            C/O Aura Dundalk                            Dundalk               Co. Louth IRL               N08
D01        Kasozi, Skye                30029218        0208200714FF  503  1C1314           41.94S                                                            N45
D330029218                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Kasozi, Skye                30029218        0208200714FF  504  7C1314           37.05S                                                            N45
D01        Kasozi, Skye                30029218        0208200714FF 2005 15C1314         2:49.65S                                                            N95
D01        Kasozi, Skye                30029218        0208200714FF 1001 21C1314         1:06.51S                                                            N85
D01        Kasozi, Skye                30029218        0208200714FF  502 27C1314           34.41S                                                            N55
D01        Lapko, Alex                 30037658        1116200615MM 1003  4D15OV         1:30.60S                                                            N65
D330037658                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Lapko, Alex                 30037658        1116200615MM 2005 16D15OV         2:48.76S                                                            N85
D01        Lapko, Alex                 30037658        1116200615MM  501 20D15OV           28.66S                                                            N45
D01        Lapko, Alex                 30037658        1116200615MM 1001 22D15OV         1:04.56S                                                            N75
D01        Lapko, Alex                 30037658        1116200615MM  502 28D15OV           31.23S                                                            N45
D01        Lapko, Alex                 30037658        1116200615MM 1002 30D15OV         1:09.97S                                                            N75
D01        Mullen, Sadhbh              30038714        0705200615FF 1003  3D15OV         1:44.05S                                                            N66
D330038714                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Mullen, Sadhbh              30038714        0705200615FF  504  7D15OV           37.48S                                                            N46
D01        Mullen, Sadhbh              30038714        0705200615FF 1004  9D15OV         1:27.66S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF 2005 15D15OV         3:04.78S                                                            N86
D01        Mullen, Sadhbh              30038714        0705200615FF 1001 21D15OV         1:12.44S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF 2001 23D15OV         2:37.25S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF  502 27D15OV           38.53S                                                            N56
D01        Mullen, Sadhbh              30038714        0705200615FF 1002 29D15OV         1:19.56S                                                            N86
D01        Mc Evoy, AMY                30038713        1205200615FF 1003  3D15OV         1:32.64S                                                            N15
D330038713                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Mc Evoy, AMY                30038713        1205200615FF 2003  5D15OV         3:16.45S                                                            N15
D01        Mc Evoy, AMY                30038713        1205200615FF 1004  9D15OV             NT                                                              N74
D01        Mc Evoy, AMY                30038713        1205200615FF 2005 15D15OV         3:00.56S                                                            N25
D01        Mc Evoy, AMY                30038713        1205200615FF 1001 21D15OV         1:18.19S                                                            N25
D01        Mc Evoy, AMY                30038713        1205200615FF 2001 23D15OV         2:39.62S                                                            N25
D01        Mc Evoy, AMY                30038713        1205200615FF 4001 25D15OV             NT                                                              N84
D01        Goss, Conor                 30040045        0214200912MM 1003  4B1112         1:49.66S                                                            N35
D330040045                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Goss, Conor                 30040045        0214200912MM 2005 16B1112         3:18.81S                                                            N45
D01        Goss, Conor                 30040045        0214200912MM  501 20B1112           34.75S                                                            N15
D01        Goss, Conor                 30040045        0214200912MM 1001 22B1112         1:20.66S                                                            N35
D01        Goss, Conor                 30040045        0214200912MM 4001 26B1112             NT                                                              N94
D01        Goss, Conor                 30040045        0214200912MM  502 28B1112           41.25S                                                            N15
D01        Goss, Conor                 30040045        0214200912MM 1002 30B1112         1:30.63S                                                            N35
D01        Goss, Conor                 30040045        0214200912MM 2002 32B1112         3:05.55S                                                            N45
D01        Coyle, Emily                30043699        0328201011FF 2003  5B1112             NT                                                              N25
D330043699                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Coyle, Emily                30043699        0328201011FF 1004  9B1112             NT                                                              N25
D01        Coyle, Emily                30043699        0328201011FF 2005 15B1112         4:06.44S                                                            N75
D01        Coyle, Emily                30043699        0328201011FF 4005 17B1112             NT                                                              N35
D01        Coyle, Emily                30043699        0328201011FF 1001 21B1112         1:40.06S                                                            N75
D01        Coyle, Emily                30043699        0328201011FF 4001 25B1112             NT                                                              N35
D01        Coyle, Emily                30043699        0328201011FF 2002 31B1112             NT                                                              N25
D01        Friel, Rebekah              30044250        0926200615FF  504  7D15OV           39.88S                                                            N36
D330044250                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Friel, Rebekah              30044250        0926200615FF 1001 21D15OV         1:08.66S                                                            N66
D01        Friel, Rebekah              30044250        0926200615FF 2002 31D15OV         2:41.02S                                                            N66
D01        Farrell, Katie              30044251        0119200516FF  504  7D15OV           37.72S                                                            N36
D330044251                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Farrell, Katie              30044251        0119200516FF 1004  9D15OV         1:23.15S                                                            N66
D01        Farrell, Katie              30044251        0119200516FF 1005 13D15OV         1:28.74S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 2005 15D15OV         3:01.30S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 1001 21D15OV         1:13.66S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 2001 23D15OV         2:38.69S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 4001 25D15OV         5:34.15S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 1002 29D15OV         1:24.25S                                                            N76
D01        Farrell, Katie              30044251        0119200516FF 2002 31D15OV             NT                                                              N26
D01        Gilmore, Dylan              30044253        0715200516MM  503  2D15OV           36.84S                                                            N56
D330044253                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Gilmore, Dylan              30044253        0715200516MM 1003  4D15OV         1:18.90S                                                            N86
D01        Gilmore, Dylan              30044253        0715200516MM 2005 16D15OV         2:42.85S                                                            N96
D01        Gilmore, Dylan              30044253        0715200516MM  501 20D15OV           28.25S                                                            N66
D01        Gilmore, Dylan              30044253        0715200516MM 1001 22D15OV         1:04.90S                                                            N86
D01        Gilmore, Dylan              30044253        0715200516MM 2001 24D15OV         2:24.49S                                                            N96
D01        Friel, Amelie               30050121        0329200813FF 1003  3C1314         1:46.50S                                                            N85
D330050121                     X FFFFFFFFFFFFF                                                                                                               N21
D01        Friel, Amelie               30050121        0329200813FF 1004  9C1314             NT                                                              N35
D01        Friel, Amelie               30050121        0329200813FF 1001 21C1314         1:36.62S                                                            N85
D01        Friel, Amelie               30050121        0329200813FF 4001 25C1314             NT                                                              N45
D01        O'Rourke, Faye              30052372        1126200516FF  503  1D15OV           46.08S                                                            N06
D330052372                     X FFFFFFFFFFFFF                                                                                                               N31
D01        O'Rourke, Faye              30052372        1126200516FF  504  7D15OV           37.26S                                                            N06
D01        O'Rourke, Faye              30052372        1126200516FF 1004  9D15OV             NT                                                              N85
D01        O'Rourke, Faye              30052372        1126200516FF  501 19D15OV           32.18S                                                            N16
D01        O'Rourke, Faye              30052372        1126200516FF 1001 21D15OV         1:12.69S                                                            N36
D01        O'Rourke, Faye              30052372        1126200516FF 2001 23D15OV         2:39.47S                                                            N46
D01        O'Rourke, Faye              30052372        1126200516FF 4001 25D15OV         5:37.57S                                                            N46
D01        O'Rourke, Faye              30052372        1126200516FF 1002 29D15OV         1:24.46S                                                            N46
D01        O'Rourke, Sean              30052373        0706200714MM  503  2C1314           49.22S                                                            N75
D330052373                     X FFFFFFFFFFFFF                                                                                                               N31
D01        O'Rourke, Sean              30052373        0706200714MM 2005 16C1314             NT                                                              N75
D01        O'Rourke, Sean              30052373        0706200714MM  501 20C1314           33.48S                                                            N85
D01        O'Rourke, Sean              30052373        0706200714MM 1001 22C1314         1:12.10S                                                            N06
D01        O'Rourke, Sean              30052373        0706200714MM 2001 24C1314         2:39.94S                                                            N26
D01        O'Rourke, Sean              30052373        0706200714MM 4001 26C1314         5:35.53S                                                            N16
D01        O'Rourke, Sean              30052373        0706200714MM  502 28C1314           42.57S                                                            N85
D01        O'Rourke, Sean              30052373        0706200714MM 1002 30C1314         1:25.66S                                                            N16
D01        Kasozi, Shyne               30052376        0513201110FF  503  1A0910             NT                                                              N55
D330052376                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Kasozi, Shyne               30052376        0513201110FF  501 19A0910           44.31S                                                            N95
D01        Kasozi, Shyne               30052376        0513201110FF 1001 21A0910             NT                                                              N75
D01        Kasozi, Shyne               30052376        0513201110FF  502 27A0910             NT                                                              N65
D01        Kasozi, Shyne               30052376        0513201110FF 1002 29A0910             NT                                                              N75
D01        Univer, Roonald             30052377        0331201110MM  503  2A0910             NT                                                              N36
D330052377                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Univer, Roonald             30052377        0331201110MM 1003  4A0910             NT                                                              N46
D01        Univer, Roonald             30052377        0331201110MM  501 20A0910             NT                                                              N46
D01        Univer, Roonald             30052377        0331201110MM 1001 22A0910             NT                                                              N56
D01        Univer, Roonald             30052377        0331201110MM  502 28A0910             NT                                                              N56
D01        Univer, Roonald             30052377        0331201110MM 1002 30A0910             NT                                                              N56
D01        Van Collier, Julia          30052378        0614200714FF  504  7C1314           36.88S                                                            N27
D330052378                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Van Collier, Julia          30052378        0614200714FF 2005 15C1314             NT                                                              N07
D01        Van Collier, Julia          30052378        0614200714FF  501 19C1314           31.76S                                                            N27
D01        Van Collier, Julia          30052378        0614200714FF 1001 21C1314         1:12.13S                                                            N47
D01        Van Collier, Julia          30052378        0614200714FF 2001 23C1314         2:33.61S                                                            N57
D01        Van Collier, Julia          30052378        0614200714FF 4001 25C1314             NT                                                              N07
D01        Van Collier, Julia          30052378        0614200714FF 1002 29C1314         1:19.15S                                                            N57
D01        Saavedra, Cedric            30052375        1009200615MM  503  2D15OV           43.78S                                                            N17
D330052375                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Saavedra, Cedric            30052375        1009200615MM 1003  4D15OV         1:38.78S                                                            N47
D01        Saavedra, Cedric            30052375        1009200615MM 2005 16D15OV             NT                                                              N07
D01        Saavedra, Cedric            30052375        1009200615MM  501 20D15OV           32.04S                                                            N17
D01        Saavedra, Cedric            30052375        1009200615MM 1001 22D15OV         1:15.96S                                                            N47
D01        Saavedra, Cedric            30052375        1009200615MM  502 28D15OV           39.68S                                                            N27
D01        Saavedra, Cedric            30052375        1009200615MM 1002 30D15OV         1:26.37S                                                            N47
D01        Saavedra, Cedric            30052375        1009200615MM 2002 32D15OV             NT                                                              N07
D01        Friel, Hugo                 30050122        0801201011MM 1003  4B1112             NT                                                              N64
D330050122                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Friel, Hugo                 30050122        0801201011MM 2003  6B1112             NT                                                              N64
D01        Friel, Hugo                 30050122        0801201011MM 1004 10B1112             NT                                                              N74
D01        Friel, Hugo                 30050122        0801201011MM 2005 16B1112             NT                                                              N74
D01        Friel, Hugo                 30050122        0801201011MM 1001 22B1112             NT                                                              N74
D01        Mullen, Maebh               30050109        1030200912FF  503  1B1112           57.06S                                                            N55
D330050109                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Mullen, Maebh               30050109        1030200912FF 1003  3B1112             NT                                                              N35
D01        Mullen, Maebh               30050109        1030200912FF  504  7B1112             NT                                                              N35
D01        Mullen, Maebh               30050109        1030200912FF 2005 15B1112             NT                                                              N45
D01        Mullen, Maebh               30050109        1030200912FF  501 19B1112           38.55S                                                            N65
D01        Mullen, Maebh               30050109        1030200912FF 1001 21B1112         1:26.56S                                                            N95
D01        Mullen, Maebh               30050109        1030200912FF 1002 29B1112         1:37.00S                                                            N95
D01        Mullen, Maebh               30050109        1030200912FF 2002 31B1112             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF  503  1A0910             NT                                                              N35
D330058790                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Jensen, Ciara               30058790        070820129 FF 1003  3A0910             NT                                                              N35
D01        Jensen, Ciara               30058790        070820129 FF  501 19A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF 1001 21A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF  502 27A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF 1002 29A0910             NT                                                              N55
D01        Saavedra, Aldrich           30062109        1205200912MM  503  2B1112             NT                                                              N86
D330062109                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Saavedra, Aldrich           30062109        1205200912MM  501 20B1112           41.16S                                                            N17
D01        Saavedra, Aldrich           30062109        1205200912MM 1001 22B1112         1:35.53S                                                            N47
D01        Saavedra, Aldrich           30062109        1205200912MM 2001 24B1112             NT                                                              N07
D01        Saavedra, Aldrich           30062109        1205200912MM  502 28B1112             NT                                                              N96
D01        Saavedra, Aldrich           30062109        1205200912MM 1002 30B1112             NT                                                              N96
D01        Viliusyte, Adrijana         30058788        0512200714FF  503  1C1314           50.83S                                                            N18
D330058788                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Viliusyte, Adrijana         30058788        0512200714FF 1005 13C1314         1:42.93S                                                            N68
D01        Viliusyte, Adrijana         30058788        0512200714FF  501 19C1314           38.19S                                                            N38
D01        Viliusyte, Adrijana         30058788        0512200714FF 1001 21C1314             NT                                                              N08
D01        Klimkowski, Roch            30055463        0813200813MM  501 20C1314           38.79S                                                            N27
D330055463                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Klimkowski, Roch            30055463        0813200813MM 1001 22C1314             NT                                                              N96
D01        Klimkowski, Roch            30055463        0813200813MM  502 28C1314           52.76S                                                            N27
D01        Klimkowski, Roch            30055463        0813200813MM 1002 30C1314             NT                                                              N96
D01        Mullen, Odhran              30067099        103020129 MM  503  2A0910             NT                                                              N85
D330067099                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Mullen, Odhran              30067099        103020129 MM 1003  4A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM  501 20A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM 1001 22A0910             NT                                                              N06
D01        Mullen, Odhran              30067099        103020129 MM  502 28A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM 1002 30A0910             NT                                                              N06
D01        Friel, Eliza                30067101        111020129 FF  503  1A0910             NT                                                              N84
D330067101                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Friel, Eliza                30067101        111020129 FF  501 19A0910             NT                                                              N94
D01        Friel, Eliza                30067101        111020129 FF  502 27A0910             NT                                                              N94
D01        Klimkowski, Eryk            30067103        0722201011MM  503  2B1112             NT                                                              N86
D330067103                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Klimkowski, Eryk            30067103        0722201011MM  501 20B1112             NT                                                              N86
D01        Klimkowski, Eryk            30067103        0722201011MM  502 28B1112             NT                                                              N96
D01        Toner, Niamh                30075732        1021201011FF  503  1B1112             NT                                                              N94
D330075732                                                                                                                                                   N48
D01        Toner, Niamh                30075732        1021201011FF  501 19B1112             NT                                                              N15
D01        Toner, Niamh                30075732        1021201011FF  502 27B1112             NT                                                              N15
D01        Grossi, Valentina           30075731        082920129 FF  503  1A0910             NT                                                              N07
D330075731                                                                                                                                                   N48
D01        Grossi, Valentina           30075731        082920129 FF  501 19A0910             NT                                                              N27
D01        Grossi, Valentina           30075731        082920129 FF  502 27A0910             NT                                                              N27
D01        Carr, Dáibhí                30075736        1024201110MM  503  2A0910             NT                                                              N26
D330075736                                                                                                                                                   N58
D01        Carr, Dáibhí                30075736        1024201110MM  501 20A0910             NT                                                              N36
D01        Carr, Dáibhí                30075736        1024201110MM  502 28A0910             NT                                                              N36
D01        Macias O'Connell, Iollann   30075906        070420129 MM  503  2A0910             NT                                                              N09
D330075906                                                                                                                                                   N48
D01        Macias O'Connell, Iollann   30075906        070420129 MM  501 20A0910             NT                                                              N09
D01        Macias O'Connell, Iollann   30075906        070420129 MM  502 28A0910             NT                                                              N19
D01        Trimble, Rebecca            30075964        1011201011FF  503  1B1112             NT                                                              N36
D330075964                                                                                                                                                   N58
D01        Trimble, Rebecca            30075964        1011201011FF  501 19B1112             NT                                                              N46
D01        Trimble, Rebecca            30075964        1011201011FF  502 27B1112             NT                                                              N46
Z01        02Successful Build on 12-27-2021  1  1   1   1   165    30    0     0     0                                                                       N56
