A01V3      20Meet Entries                  Hy-Tek, Ltd               8.0FHy-Tek, Ltd         252-633-517712222021                                    TM41    N21
B11        Christmas Time Trial                                                      Aura Dundalk                        1228202112302021            S       N10
C11          ADSCAura Dundalk Swimming Club    ADSC            C/O Aura Dundalk                            Dundalk               Co. Louth IRL               N08
D01        Mullen, Sadhbh              30038714        0705200615FF 1003  3D15OV         1:44.05S                                                            N66
D330038714                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Mullen, Sadhbh              30038714        0705200615FF  504  7D15OV           37.48S                                                            N46
D01        Mullen, Sadhbh              30038714        0705200615FF 1004  9D15OV         1:27.66S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF 1005 13D15OV         1:27.82S                                                            N86
D01        Mullen, Sadhbh              30038714        0705200615FF 1001 21D15OV         1:12.44S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF 2001 23D15OV         2:37.25S                                                            N76
D01        Mullen, Sadhbh              30038714        0705200615FF  502 27D15OV           38.53S                                                            N56
D01        Mullen, Sadhbh              30038714        0705200615FF 1002 29D15OV         1:19.56S                                                            N86
D01        Friel, Hugo                 30050122        0801201011MM  503  2B1112         1:00.71S                                                            N05
D330050122                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Friel, Hugo                 30050122        0801201011MM 1003  4B1112             NT                                                              N64
D01        Friel, Hugo                 30050122        0801201011MM  504  8B1112           46.64S                                                            N94
D01        Friel, Hugo                 30050122        0801201011MM 1004 10B1112             NT                                                              N74
D01        Friel, Hugo                 30050122        0801201011MM 1005 14B1112         1:46.12S                                                            N25
D01        Friel, Hugo                 30050122        0801201011MM  501 20B1112           43.10S                                                            N84
D01        Friel, Hugo                 30050122        0801201011MM 1001 22B1112             NT                                                              N74
D01        Friel, Hugo                 30050122        0801201011MM  502 28B1112           51.86S                                                            N94
D01        Friel, Hugo                 30050122        0801201011MM 1002 30B1112         1:43.69S                                                            N25
D01        Mullen, Maebh               30050109        1030200912FF  503  1B1112           57.06S                                                            N55
D330050109                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Mullen, Maebh               30050109        1030200912FF 1003  3B1112             NT                                                              N35
D01        Mullen, Maebh               30050109        1030200912FF  504  7B1112             NT                                                              N35
D01        Mullen, Maebh               30050109        1030200912FF 1005 13B1112         1:41.53S                                                            N95
D01        Mullen, Maebh               30050109        1030200912FF  501 19B1112           38.55S                                                            N65
D01        Mullen, Maebh               30050109        1030200912FF 1001 21B1112         1:26.56S                                                            N95
D01        Mullen, Maebh               30050109        1030200912FF  502 27B1112           44.97S                                                            N65
D01        Mullen, Maebh               30050109        1030200912FF 1002 29B1112         1:37.00S                                                            N95
D01        Jensen, Ciara               30058790        070820129 FF  503  1A0910             NT                                                              N35
D330058790                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Jensen, Ciara               30058790        070820129 FF 1003  3A0910             NT                                                              N35
D01        Jensen, Ciara               30058790        070820129 FF 1005 13A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF  501 19A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF 1001 21A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF  502 27A0910             NT                                                              N45
D01        Jensen, Ciara               30058790        070820129 FF 1002 29A0910             NT                                                              N55
D01        Mullen, Odhran              30067099        103020129 MM  503  2A0910             NT                                                              N85
D330067099                     X FFFFFFFFFFFFF                                                                                                               N41
D01        Mullen, Odhran              30067099        103020129 MM 1003  4A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM 1005 14A0910             NT                                                              N06
D01        Mullen, Odhran              30067099        103020129 MM  501 20A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM 1001 22A0910             NT                                                              N06
D01        Mullen, Odhran              30067099        103020129 MM  502 28A0910             NT                                                              N95
D01        Mullen, Odhran              30067099        103020129 MM 1002 30A0910             NT                                                              N06
D01        Friel, Eliza                30067101        111020129 FF  503  1A0910             NT                                                              N84
D330067101                     X FFFFFFFFFFFFF                                                                                                               N31
D01        Friel, Eliza                30067101        111020129 FF  501 19A0910             NT                                                              N94
D01        Friel, Eliza                30067101        111020129 FF  502 27A0910             NT                                                              N94
Z01        02Successful Build on 12-22-2021  1  1   1   1    42     6    0     0     0                                                                       N36
